### ISSUE TITLE
Can't Run -tor

### ISSUE THREAD

**Issue by ibnufachrizal** [hahwul/gitls#7]
When i type command : `gitls -l sample.lst -tor`

> **-tor** error

output: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x104cc1214]

goroutine 1 [running]:
github.com/hahwul/gitls/pkg/modules.GetRepoListFromUser({0x1400014608b, 0x5}, {0x14000146080, 0xa}, {{0x0, 0x0}, 0x1, {0x0, 0x0}, 0x1})
	/Users/ibnufachrizal/go/pkg/mod/github.com/hahwul/gitls@v1.0.3/pkg/modules/github.go:74 +0x1c4
github.com/hahwul/gitls/pkg/modules.CheckURL({0x14000146078, 0x18}, {{0x0, 0x0}, 0x1, {0x0, 0x0}, 0x1})
	/Users/ibnufachrizal/go/pkg/mod/github.com/hahwul/gitls@v1.0.3/pkg/modules/check.go:31 +0x104
main.main()
	/Users/ibnufachrizal/go/pkg/mod/github.com/hahwul/gitls@v1.0.3/main.go:50 +0x330
```

**Comment by hahwul** [comment]
Hi @ibnufachrizal 
The part that causes CRASH has been modified. Apart from this, it's good to know one thing about tor.

Recently, tor is used by specifying the HTTP Proxy separately through the flag `--HTTPTunnelPort`. 
Therefore, there are cases where HTTP cannot be used on 9050, so you can use it by operating it in the form below.

*tor*
```shell
tor --HTTPTunnelPort 8118
```

*gitls*
```shell
cat sample.lst | gitls -proxy http://localhost:8118
```

![](https://user-images.githubusercontent.com/13212227/190671621-88b1e018-fa1c-4ba4-ac8b-cbbddfb7c399.png)
